### ISSUE TITLE
The library is vartime on all non-amd64 platforms if built with go 1.12

### ISSUE THREAD

**Issue by Yawning** [bwesterb/go-ristretto#17]
`FieldElement.Mul` has a comment like thus: `// TODO make sure we only use bits.Add64 if it's constant-time`

While "the fallback code is vartime" has thankfully been fixed for Go 1.13 and later, the only platform where `bits.Add64` is constant time for Go 1.12 series is amd64.  With Go 1.13 the only platforms where both `bits.Add64` and `bits.Mul64` are fast is limited to amd64, arm64, and ppc64 (for both endian configurations), but at least they are guaranteed to be constant time now.

See:
 * https://github.com/golang/go/blob/release-branch.go1.12/src/math/bits/bits.go#L363
 * https://github.com/golang/go/blob/release-branch.go1.12/src/cmd/compile/internal/gc/ssa.go#L3500
 * https://github.com/golang/go/blob/release-branch.go1.13/src/cmd/compile/internal/gc/ssa.go#L3587

**Comment by bwesterb** [comment]
Thanks!  I've changed the build flags to only use `bits.Add64` on Go 1.13 onwards.  That should fix it, right?

**Comment by Yawning** [comment]
Yep, that'll do it.  I would call this issue fixed.

As a side note, I don't think the `go 1.13` annotation in go.mod is required (compilation will fail with older versions of the toolchain, when the fallback code is now fine).

**Comment by bwesterb** [comment]
Most annoyingly Go 1.13 automatically adds the annotation if it's missing.  The build doesn't seem to fail [on old version](https://travis-ci.org/bwesterb/go-ristretto/builds/589062891?utm_source=github_status&utm_medium=notification), but that might perhaps be because it still uses the old Go path mechanism.
