### ISSUE TITLE
Point.Equals() always returns true if at least one point is uninitialized.

### ISSUE THREAD

**Issue by jiajun1992** [bwesterb/go-ristretto#19]
var a, b ristretto.Point
b.Rand()
flag := a.Equals(b) 
flag is true.

**Comment by bwesterb** [comment]
You should never use an uninitialised point as an argument.  Operations with an uninitialised point are undefined.  Unfortunately Go makes it hard to prevent the use of uninitialised points without sacrificing quite a bit of performance.

**Comment by jiajun1992** [comment]
I agree. There is no easy way to fix it without sacrificing quite a bit of performance. But I guess point compare is not always used in most protocols. Maybe, it can be more robust if there is a check, or another interface like EqualsUnsafe is provided to replace current one, or some comments can be provided. Go sometimes implies people that uninitialized object is zero. In this case, there is difference between point.SetZero() and uninitialized point.

**Comment by bwesterb** [comment]
And for `big.Int`s, to which I've modelled the API, a zero value is actually valid.  I've added two warnings.

**Comment by bwesterb** [comment]
In a few protocols (that I've implemented) it's actually quite important that a given Point is not the neutral point, for which I use this check.

**Comment by jiajun1992** [comment]
Thanks for building and maintaining this lib! Cheers!
