### ISSUE TITLE
how to encode message into point on curve

### ISSUE THREAD

**Issue by liqiang000** [bwesterb/go-ristretto#24]
@bwesterb Hi，bwesterb. I wanna implement Elgamal encryption with this library, but it confuses me that how to encode message into point on curve. Is there any sample for this usage. I saw the provided example, but it can not answer my need.
 
Looking forward to your reply.

**Comment by bwesterb** [comment]
There is not a straight-forward to encode messages into the curve.  There is a "hack", see  https://pkg.go.dev/github.com/bwesterb/go-ristretto#Point.SetLizard

But if you want to do PKE, then you don't need to encode a message into the curve — you can just use a random point as a key to encrypt the message symmetrically.

**Comment by liqiang000** [comment]
@bwesterb you mean hybrid encryption, encrypting message with symmetric key. But i wanna homomorphism property.

**Comment by bwesterb** [comment]
Then use Lizard or have a look at the elligator inverse.
